Asp.NETMVCCRUD/Controllers/NasabahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Asp.NETMVCCRUD.Models;
using System.Data.Entity;

namespace Asp.NETMVCCRUD.Controllers
{
    public class NasabahController : Controller
    {
        //
        // GET: /tm_Operator/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            using (OCBCTestEntities1 db = new OCBCTestEntities1())
            {
                List<tm_Nasabah> empList = db.tm_Nasabah.Where(x => x.Status_FK == 1).ToList<tm_Nasabah>();
                return Json(new { data = empList }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new tm_Nasabah());
            else
            {
                using (OCBCTestEntities1 db = new OCBCTestEntities1())
                {
                    return View(db.tm_Nasabah.Where(x => x.AccountID==id).FirstOrDefault<tm_Nasabah>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(tm_Nasabah emp)
        {
            using (OCBCTestEntities1 db = new OCBCTestEntities1())
            {
                if (emp.Status_FK == 0)
                {
                    emp.Status_FK = 1;
                    db.tm_Nasabah.Add(emp);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else {
                    db.Entry(emp).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }


        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (OCBCTestEntities1 db = new OCBCTestEntities1())
            {
                tm_Nasabah emp = db.tm_Nasabah.Where(x => x.AccountID == id).FirstOrDefault<tm_Nasabah>();
                emp.Status_FK = 2;
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Asp.NETMVCCRUD/Controllers/TransaksiController.cs
using Asp.NETMVCCRUD.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NETMVCCRUD.Controllers
{
    public class TransaksiController : Controller
    {
        // GET: Transaksi
        public ActionResult InputPage(int id)
        {
            if (id == 0)
            {
                return RedirectToAction("Index", "Nasabah");
            }
            else
            {
                using (OCBCTestEntities1 db = new OCBCTestEntities1())
                {
                    tm_Nasabah emp = db.tm_Nasabah.Where(x => x.AccountID == id).FirstOrDefault<tm_Nasabah>();
                    return View(emp);
                }
            }
        }

        public ActionResult GetData(int id)
        {
            List<Transaksi> res = new List<Transaksi>();
            using (OCBCTestEntities1 db = new OCBCTestEntities1())
            {
                res = (from x in db.tt_Transaction
                       where x.AccountID == id
                       select new Transaksi
                       {
                           TransactionID = x.TransactionID,
                           AccountID = x.AccountID,
                           TransDate = x.TransDate.ToString(),
                           Description = x.Description,
                           DebitCreditStatus = x.DebitCreditStatus,
                           Amount = x.Amount
                       }).ToList();

            }
            return Json(new { data = res }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new tt_Transaction());
            else
            {
                using (OCBCTestEntities1 db = new OCBCTestEntities1())
                {
                    return View(db.tt_Transaction.Where(x => x.TransactionID == id).FirstOrDefault<tt_Transaction>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(tt_Transaction emp)
        {
            using (OCBCTestEntities1 db = new OCBCTestEntities1())
            {
                if (emp.TransactionID == 0)
                {
                    db.tt_Transaction.Add(emp);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(emp).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }


        }

        public ActionResult Create()
        {
            return PartialView();
        }
    }
}

Asp.NETMVCCRUD/Views/Nasabah/AddOrEdit.cshtml
@model Asp.NETMVCCRUD.Models.tm_Nasabah
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Nasabah", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.Status_FK)
    if (Model.AccountID == 0)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.AccountID, new { @class = "control-label" })
            @Html.EditorFor(model => model.AccountID, new { htmlAttributes = new { @class = "form-control", @Value = "" } })
            @Html.ValidationMessageFor(model => model.AccountID)
        </div>
    }
    else
    {
        <div class="form-group">
            @Html.LabelFor(model => model.AccountID, new { @class = "control-label" })
            @Html.EditorFor(model => model.AccountID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AccountID)
        </div>
    }


    <div class="form-group">
        @Html.LabelFor(model => model.Nama, new { @class = "control-label" })
        @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn" />
    </div>
}

Asp.NETMVCCRUD/Views/Nasabah/Index.cshtml
@{
    ViewBag.Title = "Nasabah List";
}

<h2>Nasabah</h2>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Nasabah")')"><i class="fa fa-plus"></i> Add New</a>
<table id="NasabahTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th></th>
        </tr>
    </thead>
</table>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

    <script>
        var Popup, dataTable;
        $(document).ready(function () {
            dataTable =  $("#NasabahTable").DataTable({
                "ajax": {
                    "url": "/Nasabah/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "AccountID" },
                    { "data": "Nama" },
                    {
                        "data":"AccountID" , "render" : function (data) {
                            return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","Nasabah")/" + data + "')><i class='fa fa-pencil'></i> Edit</a>" +
                                "<a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete(" + data + ")><i class='fa fa-trash'></i> Delete</a>" +
                                "<a class='btn btn-primary btn-sm' onclick=ChangePage('@Url.Action("InputPage","Transaksi")/" + data + "')><i class='fa fa-info'></i> Transaction</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"150px"
                    }

                ],
                "language": {

                    "emptyTable" : "No data found, Please click on <b>Add New</b> Button"
                },
                "columnDefs": [{
                    "searchable": false,
                    "orderable": false,
                    "targets": 0
                }],
                "order": [[1, 'desc']]
            });
            dataTable.on('order.dt search.dt', function () {
                dataTable.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1;
                });
            }).draw();
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,
                    title: 'Fill Nasabah Details',
                    height: 350,
                    width: 700,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }

                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if($(form).valid()){
                $.ajax({
                    type : "POST",
                    url : form.action,
                    data : $(form).serialize(),
                    success : function (data) {
                        if(data.success)
                        {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message,{
                                globalPosition :"top center",
                                className : "success"
                            })

                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if(confirm('Are You Sure to Delete this Nasabah Record ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Nasabah")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }

        function ChangePage(x) {
            window.location.href = x;
        }
    </script>
}